import { defineArrayMember, defineField, defineType } from 'sanity';
import {
  campoBloquesLocalizados,
  campoLocalizado,
  campoSlug,
  campoSlugsAnteriores,
  validarPesoVideo,
} from '../ayudantes';

const MB = 1_048_576;

export const venue = defineType({
  name: 'venue',
  title: 'Venue',
  type: 'document',
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'ficha', title: 'Ficha técnica' },
    { name: 'media', title: 'Fotos y video' },
    { name: 'entrevista', title: 'Entrevista' },
    { name: 'espacios', title: 'Espacios y citas' },
    { name: 'relaciones', title: 'Proveedores' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'nombre',
      title: 'Nombre',
      description: 'Nombre propio del venue: se muestra igual en ambos idiomas.',
      type: 'string',
      group: 'general',
      validation: (r) => r.required().max(80),
    }),
    campoSlug('nombre', 'general'),
    campoSlugsAnteriores('general'),
    defineField({
      name: 'publicado',
      title: 'Visible en el sitio',
      description:
        'Apágalo para ocultar el venue sin borrarlo (por ejemplo, si deja de ser aliado).',
      type: 'boolean',
      group: 'general',
      initialValue: true,
    }),
    defineField({
      name: 'destacado',
      title: 'Destacado en el inicio',
      description: 'Decisión editorial, independiente del nivel comercial (D-015).',
      type: 'boolean',
      group: 'general',
      initialValue: false,
    }),
    defineField({
      name: 'nivelListado',
      title: 'Nivel de listado',
      description:
        'Plan comercial: define los bloques visibles y la prioridad en el orden "destacados".',
      type: 'string',
      group: 'general',
      options: {
        list: [
          { title: 'Básico', value: 'basico' },
          { title: 'Video', value: 'video' },
          { title: 'Destacado', value: 'destacado' },
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'basico',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'region',
      title: 'Región',
      type: 'reference',
      to: [{ type: 'region' }],
      group: 'general',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'tipos',
      title: 'Tipos',
      type: 'array',
      group: 'general',
      of: [defineArrayMember({ type: 'string' })],
      options: {
        list: [
          { title: 'Hacienda', value: 'hacienda' },
          { title: 'Ciudad colonial', value: 'ciudad-colonial' },
          { title: 'Playa', value: 'playa' },
          { title: 'Cenote y selva', value: 'cenote-selva' },
          { title: 'Boutique', value: 'boutique' },
          { title: 'Otro', value: 'otro' },
        ],
      },
      validation: (r) => r.required().min(1),
    }),
    campoLocalizado({
      name: 'resumen',
      title: 'Resumen',
      description: 'Aparece en tarjetas y en el encabezado de la ficha.',
      largo: true,
      max: 200,
      group: 'general',
    }),
    campoBloquesLocalizados({ name: 'descripcion', title: 'Descripción', group: 'general' }),
    defineField({
      name: 'fichaTecnica',
      title: 'Ficha técnica',
      type: 'fichaTecnica',
      group: 'ficha',
    }),
    defineField({
      name: 'media',
      title: 'Fotos y video',
      type: 'object',
      group: 'media',
      fields: [
        defineField({
          name: 'imagenHero',
          title: 'Imagen principal',
          type: 'imagenConAlt',
          validation: (r) => r.required(),
        }),
        defineField({
          name: 'videoLoop',
          title: 'Video loop (escritorio)',
          description: 'MP4 o WebM sin audio, máximo 2 MB (D-014). Opcional.',
          type: 'file',
          options: { accept: 'video/mp4,video/webm' },
          validation: validarPesoVideo(2 * MB),
        }),
        defineField({
          name: 'videoLoopMovil',
          title: 'Video loop (móvil)',
          description: 'Versión ligera, máximo 1 MB. Si falta, en móvil solo se ve la imagen.',
          type: 'file',
          options: { accept: 'video/mp4,video/webm' },
          validation: validarPesoVideo(MB),
        }),
        defineField({
          name: 'galeria',
          title: 'Galería',
          type: 'array',
          of: [defineArrayMember({ type: 'imagenConAlt' })],
          options: { layout: 'grid' },
        }),
      ],
    }),
    defineField({
      name: 'entrevista',
      title: 'Entrevista',
      description: 'Solo se muestra en los niveles "Video" y "Destacado".',
      type: 'object',
      group: 'entrevista',
      fields: [
        defineField({
          name: 'youtubeId',
          title: 'ID del video de YouTube',
          description: 'Los 11 caracteres después de "v=" en la URL.',
          type: 'string',
          validation: (r) => r.regex(/^[\w-]{11}$/, { name: 'ID de YouTube' }),
        }),
        campoLocalizado({ name: 'titulo', title: 'Título del video', max: 100, requerido: false }),
        defineField({
          name: 'capitulos',
          title: 'Capítulos',
          type: 'array',
          of: [defineArrayMember({ type: 'capitulo' })],
        }),
      ],
    }),
    defineField({
      name: 'espacios',
      title: 'Espacios',
      type: 'array',
      group: 'espacios',
      of: [defineArrayMember({ type: 'espacio' })],
    }),
    defineField({
      name: 'citasDestacadas',
      title: 'Citas destacadas',
      type: 'array',
      group: 'espacios',
      of: [defineArrayMember({ type: 'cita' })],
      validation: (r) => r.max(4),
    }),
    defineField({
      name: 'proveedoresRecomendados',
      title: 'Proveedores recomendados',
      type: 'array',
      group: 'relaciones',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'proveedor' }] })],
      validation: (r) => r.unique().max(6),
    }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo', group: 'seo' }),
  ],
  orderings: [{ title: 'Nombre', name: 'nombre', by: [{ field: 'nombre', direction: 'asc' }] }],
  preview: {
    select: {
      title: 'nombre',
      region: 'region.nombre.en',
      publicado: 'publicado',
      media: 'media.imagenHero',
    },
    prepare: ({ title, region, publicado, media }) => ({
      title,
      subtitle: `${region ?? 'Sin región'}${publicado === false ? ' · oculto' : ''}`,
      media,
    }),
  },
});
