import { defineArrayMember, defineField, defineType } from 'sanity';
import {
  campoBloquesLocalizados,
  campoLocalizado,
  campoSlug,
  campoSlugsAnteriores,
  validarPesoVideo,
} from '../ayudantes';

const MB = 1_048_576;

/** Perfil de venue (documento de estructura, secciones 6 y 7). */
export const venue = defineType({
  name: 'venue',
  title: 'Venue',
  type: 'document',
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'datos', title: 'Datos clave' },
    { name: 'espacios', title: 'Espacios y notas' },
    { name: 'media', title: 'Fotos y video' },
    { name: 'pelicula', title: 'Película' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'nombre',
      title: 'Nombre',
      description: 'Nombre propio del venue: se muestra igual en ambos idiomas.',
      type: 'string',
      group: 'general',
      validation: (r) => r.required().max(80),
    }),
    campoSlug('nombre', 'general'),
    campoSlugsAnteriores('general'),
    defineField({
      name: 'publicado',
      title: 'Visible en el sitio',
      description: 'Apágalo para ocultar el venue sin borrarlo.',
      type: 'boolean',
      group: 'general',
      initialValue: true,
    }),
    defineField({
      name: 'destacado',
      title: 'Destacado en el inicio',
      description: 'Decisión editorial (D-015). El inicio muestra de 4 a 6 venues destacados.',
      type: 'boolean',
      group: 'general',
      initialValue: false,
    }),
    defineField({
      name: 'coleccion',
      title: 'Colección (estilo)',
      description: 'La categoría del libro. Ordena el listado y el resultado de Find Your Yucatán.',
      type: 'reference',
      to: [{ type: 'coleccion' }],
      group: 'general',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'region',
      title: 'Ubicación (región)',
      type: 'reference',
      to: [{ type: 'region' }],
      group: 'general',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'localidad',
      title: 'Localidad o municipio',
      description: 'Nombre propio, por ejemplo "Chocholá".',
      type: 'string',
      group: 'general',
      validation: (r) => r.required().max(60),
    }),
    campoLocalizado({
      name: 'resumen',
      title: 'Resumen',
      description: 'Para buscadores y redes (máximo 200 caracteres).',
      largo: true,
      max: 200,
      group: 'general',
    }),
    campoBloquesLocalizados({
      name: 'descripcion',
      title: 'Descripción (About)',
      group: 'general',
    }),
    defineField({
      name: 'atributos',
      title: 'Lo que lo distingue',
      description: 'Se usa en "What matters most?" de Find Your Yucatán. Elige los más evidentes.',
      type: 'array',
      group: 'general',
      of: [defineArrayMember({ type: 'string' })],
      options: {
        list: [
          { title: 'Arquitectura', value: 'arquitectura' },
          { title: 'Naturaleza', value: 'naturaleza' },
          { title: 'Gastronomía', value: 'gastronomia' },
          { title: 'Privacidad', value: 'privacidad' },
          { title: 'Ubicación', value: 'ubicacion' },
        ],
      },
      validation: (r) => r.unique().max(3),
    }),
    defineField({
      name: 'fichaTecnica',
      title: 'Datos clave',
      type: 'fichaTecnica',
      group: 'datos',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'espacios',
      title: 'Espacios',
      type: 'array',
      group: 'espacios',
      of: [defineArrayMember({ type: 'espacio' })],
    }),
    defineField({
      name: 'notasCurated',
      title: 'Curated Notes',
      description: 'Información especialmente útil para wedding planners.',
      type: 'array',
      group: 'espacios',
      of: [defineArrayMember({ type: 'notaCurated' })],
      validation: (r) => r.max(6),
    }),
    defineField({
      name: 'media',
      title: 'Fotos y video',
      type: 'object',
      group: 'media',
      fields: [
        defineField({
          name: 'imagenHero',
          title: 'Imagen principal',
          type: 'imagenConAlt',
          validation: (r) => r.required(),
        }),
        defineField({
          name: 'videoLoop',
          title: 'Video loop (escritorio)',
          description: 'MP4 o WebM sin audio, máximo 2 MB (D-014). Opcional.',
          type: 'file',
          options: { accept: 'video/mp4,video/webm' },
          validation: validarPesoVideo(2 * MB),
        }),
        defineField({
          name: 'videoLoopMovil',
          title: 'Video loop (móvil)',
          description: 'Versión ligera, máximo 1 MB. Si falta, en móvil solo se ve la imagen.',
          type: 'file',
          options: { accept: 'video/mp4,video/webm' },
          validation: validarPesoVideo(MB),
        }),
        defineField({
          name: 'galeria',
          title: 'Galería',
          type: 'array',
          of: [defineArrayMember({ type: 'imagenConAlt' })],
          options: { layout: 'grid' },
        }),
      ],
    }),
    defineField({
      name: 'pelicula',
      title: 'Película (El Lugar de Tu Historia)',
      description: 'El video del venue en la serie de YouTube.',
      type: 'object',
      group: 'pelicula',
      fields: [
        defineField({
          name: 'youtubeId',
          title: 'ID del video de YouTube',
          description: 'Los 11 caracteres después de "v=" en la URL.',
          type: 'string',
          validation: (r) => r.regex(/^[\w-]{11}$/, { name: 'ID de YouTube' }),
        }),
        campoLocalizado({ name: 'titulo', title: 'Título del video', max: 100, requerido: false }),
        defineField({
          name: 'capitulos',
          title: 'Capítulos',
          type: 'array',
          of: [defineArrayMember({ type: 'capitulo' })],
        }),
      ],
    }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo', group: 'seo' }),
  ],
  orderings: [{ title: 'Nombre', name: 'nombre', by: [{ field: 'nombre', direction: 'asc' }] }],
  preview: {
    select: {
      title: 'nombre',
      coleccion: 'coleccion.nombre.en',
      publicado: 'publicado',
      media: 'media.imagenHero',
    },
    prepare: ({ title, coleccion, publicado, media }) => ({
      title,
      subtitle: `${coleccion ?? 'Sin colección'}${publicado === false ? ' · oculto' : ''}`,
      media,
    }),
  },
});
